language: node_js
node_js:
  - "7.2"
  - "6.9"
  - "4.6"
  - "0.12"
  - "0.10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: npm test --coverage
after_success:
  - npm run coveralls
